apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: {{ grafana_namespace }}
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ prometheus_url }}
        isDefault: true
