---
- name: Test different Kubernetes repository approaches
  hosts: k8_worker
  become: true
  vars:
    k8s_version: "1.29"
  tasks:
    - name: Create APT keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Ensure gpg is installed
      ansible.builtin.apt:
        name: gnupg
        state: present

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    - name: Try legacy apt.kubernetes.io repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes-legacy

    - name: Update APT cache for legacy repo
      ansible.builtin.apt:
        update_cache: true
      register: legacy_update

    - name: Display legacy repo result
      ansible.builtin.debug:
        var: legacy_update

    - name: Check if kubelet packages are available from legacy repo
      ansible.builtin.shell: |
        apt-cache search "kubelet={{ k8s_version }}" | head -5
      register: kubelet_check
      changed_when: false

    - name: Display kubelet availability
      ansible.builtin.debug:
        var: kubelet_check.stdout_lines

    - name: Check what's actually available
      ansible.builtin.shell: |
        apt-cache search kubernetes | grep -E "(kubelet|kubeadm|kubectl)" | head -10
      register: available_packages
      changed_when: false

    - name: Display available packages
      ansible.builtin.debug:
        var: available_packages.stdout_lines 