- name: Deploy Grafana and Prometheus stack
  hosts: control_plane
  become: yes
  gather_facts: yes

  vars:
    prometheus_namespace: prometheus
    grafana_namespace: prometheus
    prometheus_configmap_name: prometheus-config
    prometheus_scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node1:9100', 'node2:9100']

  roles:
    # - prometheus
    - grafana
