- name: Render and debug Grafana ConfigMap
  debug:
    msg: "{{ lookup('template', role_path + '/files/grafana-datasource-configmap.yml.j2') }}"
    tags: debug_configmap

- name: Create Grafana namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ grafana_namespace }}"
    state: present

- name: Apply Grafana dashboard ConfigMap
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'grafana-dashboard-configmap.yml.j2') | from_yaml }}"
    state: present

- name: Apply Grafana datasource ConfigMap
  kubernetes.core.k8s:
    definition: "{{ lookup('file', role_path + '/files/grafana-datasource-configmap.yml') | from_yaml }}"
    state: present

- name: Create Grafana PVC
  kubernetes.core.k8s:
    src: "{{ role_path }}/files/grafana-pvc.yml"
    state: present

- name: Deploy Grafana
  kubernetes.core.k8s:
    src: "{{ role_path }}/templates/grafana-deployment.yml.j2"
    state: present

- name: Expose Grafana via NodePort
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana
        namespace: "{{ grafana_namespace }}"
      spec:
        type: NodePort
        selector:
          app: grafana
        ports:
          - port: 3000
            targetPort: 3000
            nodePort: "{{ grafana_node_port }}"
    state: present
