---
- name: "[Worker] Wait for control plane kubeadm token"
  wait_for:
    path: /etc/kubernetes/admin.conf
    host: "{{ groups['control_plane'][0] }}"
    search_regex: '.*'
    timeout: 300
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true

- name: "[Worker] Retrieve kubeadm join command from control plane"
  shell: kubeadm token create --print-join-command
  args:
    executable: /bin/bash
  register: join_cmd
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true

- name: "[Worker] Join node to the cluster"
  command: "{{ join_cmd.stdout }} --ignore-preflight-errors=all"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: join_workers
